coverage_service: cobertura_xml
output_directory: ./
source_directory:
  - Domain
  - Presentation
binary_basename:
  - Domain
  - Presentation

workspace: CeibaParking.xcworkspace
scheme: Presentation
xcodeproj: Presentation/Presentation.xcodeproj